/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/bronco.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Bronco(props) {
  const { nodes, materials } = useGLTF('./models/bronco.glb');
  const myModel = useRef()

  useFrame(({ clock }) => {
    myModel.current.rotation.y = clock.getElapsedTime() * 0.5;
    myModel.current.rotation.z = clock.getElapsedTime() * 0.25;
  })

  return (
    <group {...props} dispose={null} ref={myModel}>
      <mesh geometry={nodes.path14.geometry} material={materials['Material.001']} position={[-2.918, -0.869, 2.263]} scale={22.021} />
      <mesh geometry={nodes.path16.geometry} material={materials['Material.006']} position={[-2.918, -0.869, 2.263]} scale={22.021} />
      <mesh geometry={nodes.path18.geometry} material={materials['Material.007']} position={[-2.918, -0.869, 2.263]} scale={22.021} />
      <mesh geometry={nodes.path20.geometry} material={materials['Material.008']} position={[-2.918, -0.869, 2.263]} scale={22.021} />
    </group>
  )
}

useGLTF.preload('./models/bronco.glb')
